# Site settings
title: "Giorgos Katsiampas Resume"
description: "Find out informations about me, education, experience, projects, technologies involved and more!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Giorgos Katsiampas"
resume_title:                   "Front-end Developer. SEO hacker."
resume_contact_email:
  "katsampukas@gmail.com"
resume_header_contact_info: "Arachova Viotias, Greece | 32004 | katsampukas@gmail.com"
resume_header_intro: |
  <p>
    I am Senior Front-End developer at <a href="https://skroutz.gr" target="_blank">Skroutz.gr</a>.
    To the time being, we have complete 2 major redesigns in the period 2011-2016,
    we have develop an internal CSS framework, and we have expose the application
    in Turkey and United Kingdom!<br>
    HTML, CSS / SCSS master, JS, Ruby / Ruby on Rails sufficient.
    I love to build web apps using cutting edge technologies.<br>
    Studied Environmentalist, MSc in Water Resources Technologies,
    I followed my dream to build things in a space that everyone will be able to see.
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/katsampukas"
  resume_twitter_url:           "http://twitter.com/katsampu"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/giorgos-katsiampas-8a833911a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://katsampu.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
